### ISSUE TITLE
A joint statement from partners from 18 EU member states

### ISSUE THREAD

**Issue by JoCriSem** [bro256/Awesome-PQC-Resources#1]
[PQC-joint-statement.pdf](https://github.com/user-attachments/files/17980182/PQC-joint-statement.pdf)

Thank you for assembling this.  You may want to add this document and the links on the last page.

**Comment by bro256** [comment]
Thank you for suggestion. The link to pdf you mentioned is already included in the list. BTW I have added some links from the last page.
